import type { IncomingMessage, ServerResponse } from "node:http";
import type { CustomRoute } from "@slack/bolt";
import type { KeptOrchestrator } from "../app/orchestrator.js";
import type { TrustView, TrustItem, TrustBucket } from "../app/trustView.js";
import { TRUST_BUCKETS } from "../app/trustView.js";
import { detectLeaks } from "../policy/audience.js";

/**
 * W6 — the customer trust page (HTTP surface). `GET /trust/:token` resolves the opaque
 * capability to an audience-safe `TrustView` (built in `src/app/trustView.ts`, gated by
 * the SAME D1 policy as the customer channel) and renders a small, self-contained,
 * branded HTML page matching the Vercel design tokens (paper / teal, Fraunces / IBM Plex).
 *
 * Response discipline: `X-Robots-Tag: noindex` + `Cache-Control: private, no-store` on
 * every response; a per-IP rate limit; and an identical 404 for unknown AND revoked
 * tokens (no existence leak). A "generated by Kept" footer signs the page.
 */

// --- design tokens (mirror docs/index.html) ---
const PAPER = "#F4F1EA";
const INK = "#1B1A17";
const TEAL = "#0F6E5C";
const MUTED = "#837C6E";

const BUCKET_META: Record<TrustBucket, { label: string; accent: string; tint: string }> = {
  kept: { label: "Kept", accent: TEAL, tint: "rgba(15,110,92,0.10)" },
  in_progress: { label: "In progress", accent: "#8A6D1F", tint: "rgba(138,109,31,0.10)" },
  verifying: { label: "Verifying", accent: "#3A5A9B", tint: "rgba(58,90,155,0.10)" },
  at_risk: { label: "At risk", accent: "#A23B2E", tint: "rgba(162,59,46,0.10)" },
};

const MONTHS = ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"];

function esc(s: string): string {
  return s.replace(/[&<>"']/g, (c) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" })[c]!);
}

/**
 * Fail-closed boundary (invariant #5): re-scan any free-text before it is emitted, with
 * the SAME detector the D1 sanitizer uses. `buildTrustView` already genericized leaky
 * labels; this is defense-in-depth so a bug upstream can never surface a ref/internal token.
 */
function safeText(s: string): string {
  return detectLeaks(s).length === 0 ? esc(s) : "Commitment";
}

/** Format a YYYY-MM-DD or ISO string as "Jun 30, 2026" (UTC, deterministic). */
function fmtDate(input: string | null): string | null {
  if (!input) return null;
  const d = new Date(input.length <= 10 ? `${input}T00:00:00Z` : input);
  if (Number.isNaN(d.getTime())) return null;
  return `${MONTHS[d.getUTCMonth()]} ${d.getUTCDate()}, ${d.getUTCFullYear()}`;
}

function keptMark(): string {
  // Inline the Kept "K" logo mark (no external asset; CSP-safe).
  return `<span class="mark">K</span>`;
}

function renderItem(item: TrustItem): string {
  const meta = BUCKET_META[item.bucket];
  const due = fmtDate(item.due);
  const keptOn = fmtDate(item.keptOn);
  const sub =
    item.bucket === "kept" && keptOn
      ? `Kept on ${esc(keptOn)}`
      : due
        ? `Due ${esc(due)}`
        : "In our ledger";
  return `
      <li class="row">
        <span class="pill" style="color:${meta.accent};background:${meta.tint};">${esc(meta.label)}</span>
        <span class="body">
          <span class="label">${safeText(item.label)}</span>
          <span class="sub">${sub}</span>
        </span>
      </li>`;
}

function renderCounts(view: TrustView): string {
  return TRUST_BUCKETS.map((b) => {
    const meta = BUCKET_META[b];
    return `
        <div class="stat">
          <div class="stat-n" style="color:${meta.accent};">${view.counts[b]}</div>
          <div class="stat-l">${esc(meta.label)}</div>
        </div>`;
  }).join("");
}

const PAGE_CSS = `
  :root{color-scheme:light;}
  *{box-sizing:border-box;}
  body{margin:0;background:${PAPER};color:${INK};font-family:'IBM Plex Sans',-apple-system,system-ui,sans-serif;font-size:16px;-webkit-font-smoothing:antialiased;text-rendering:optimizeLegibility;line-height:1.5;}
  .wrap{max-width:720px;margin:0 auto;padding:48px 24px 64px;}
  header{display:flex;align-items:center;gap:10px;margin-bottom:36px;}
  .mark{width:28px;height:28px;border-radius:7px;background:${TEAL};color:${PAPER};display:inline-flex;align-items:center;justify-content:center;font-family:'IBM Plex Mono','SF Mono',Menlo,monospace;font-weight:600;font-size:16px;}
  .brand{font-family:'Fraunces',Georgia,serif;font-weight:600;font-size:20px;letter-spacing:-0.01em;}
  h1{font-family:'Fraunces',Georgia,serif;font-weight:600;font-size:32px;line-height:1.15;letter-spacing:-0.02em;margin:0 0 6px;}
  .lede{color:${MUTED};font-size:15px;margin:0 0 32px;}
  .stats{display:grid;grid-template-columns:repeat(4,1fr);gap:12px;margin:0 0 40px;}
  .stat{background:rgba(0,0,0,0.02);border:1px solid rgba(0,0,0,0.06);border-radius:12px;padding:16px 12px;text-align:center;}
  .stat-n{font-family:'Fraunces',Georgia,serif;font-weight:600;font-size:28px;line-height:1;}
  .stat-l{font-family:'IBM Plex Mono',monospace;font-size:11px;letter-spacing:0.04em;text-transform:uppercase;color:${MUTED};margin-top:8px;}
  section{margin:0 0 28px;}
  h2{font-family:'IBM Plex Mono',monospace;font-size:12px;letter-spacing:0.08em;text-transform:uppercase;color:${MUTED};margin:0 0 12px;font-weight:500;}
  ul{list-style:none;margin:0;padding:0;}
  .row{display:flex;gap:14px;align-items:flex-start;padding:16px 0;border-top:1px solid rgba(0,0,0,0.08);}
  .row:first-child{border-top:none;}
  .pill{flex:0 0 auto;font-family:'IBM Plex Mono',monospace;font-size:11px;letter-spacing:0.03em;padding:4px 10px;border-radius:999px;white-space:nowrap;margin-top:2px;}
  .body{display:flex;flex-direction:column;gap:3px;}
  .label{font-size:16px;font-weight:500;}
  .sub{color:${MUTED};font-size:13px;font-family:'IBM Plex Mono',monospace;}
  .empty{color:${MUTED};font-size:15px;padding:28px 0;text-align:center;border:1px dashed rgba(0,0,0,0.12);border-radius:12px;}
  footer{margin-top:48px;padding-top:20px;border-top:1px solid rgba(0,0,0,0.08);color:${MUTED};font-size:12px;font-family:'IBM Plex Mono',monospace;display:flex;flex-wrap:wrap;gap:6px 14px;align-items:center;justify-content:space-between;}
  footer .gen{display:inline-flex;align-items:center;gap:7px;}
  footer .dot{width:16px;height:16px;border-radius:4px;background:${TEAL};color:${PAPER};display:inline-flex;align-items:center;justify-content:center;font-weight:600;font-size:10px;}
`;

function shell(title: string, body: string): string {
  return `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="robots" content="noindex, nofollow">
<title>${esc(title)}</title>
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Fraunces:opsz,wght@9..144,400;9..144,500;9..144,600&family=IBM+Plex+Sans:wght@400;500;600&family=IBM+Plex+Mono:wght@400;500&display=swap" rel="stylesheet">
<style>${PAGE_CSS}</style>
</head>
<body><div class="wrap">${body}</div></body>
</html>`;
}

function footer(view?: TrustView): string {
  const withheld =
    view && view.redactedInternalCount > 0
      ? `${view.redactedInternalCount} internal detail${view.redactedInternalCount === 1 ? "" : "s"} withheld`
      : "Internal details are never shown here";
  const stamp = view ? `Generated ${esc(fmtDate(view.generatedAt) ?? "")}` : "";
  return `
    <footer>
      <span class="gen"><span class="dot">K</span> Generated by Kept</span>
      <span>${esc(withheld)}${stamp ? ` · ${stamp}` : ""}</span>
    </footer>`;
}

/** Render the audience-safe trust page for one customer. */
export function renderTrustPage(view: TrustView): string {
  const bySection = TRUST_BUCKETS.map((bucket) => {
    const rows = view.items.filter((it) => it.bucket === bucket);
    if (rows.length === 0) return "";
    return `
      <section>
        <h2>${esc(BUCKET_META[bucket].label)} · ${rows.length}</h2>
        <ul>${rows.map(renderItem).join("")}</ul>
      </section>`;
  }).join("");

  const body = `
    <header>${keptMark()}<span class="brand">Kept</span></header>
    <h1>Commitments to ${safeText(view.customer)}</h1>
    <p class="lede">A live, human-verified view of what we've promised you and where each promise stands.</p>
    <div class="stats">${renderCounts(view)}</div>
    ${view.items.length === 0 ? `<div class="empty">No open commitments on record right now.</div>` : bySection}
    ${footer(view)}`;

  return shell(`Commitments to ${view.customer} · Kept`, body);
}

/** The 404 page — identical for unknown AND revoked tokens (no existence leak). */
export function renderTrustNotFound(): string {
  const body = `
    <header>${keptMark()}<span class="brand">Kept</span></header>
    <h1>This link isn't available</h1>
    <p class="lede">The link may have expired or been revoked. Please ask your account team for a fresh one.</p>
    ${footer()}`;
  return shell("Not available · Kept", body);
}

/**
 * A simple in-memory fixed-window rate limiter (best-effort, per instance). Enough to
 * blunt scraping/abuse of the public route; not a distributed limiter.
 */
export class TrustRateLimiter {
  private readonly hits = new Map<string, { count: number; resetAt: number }>();
  constructor(
    private readonly limit = 60,
    private readonly windowMs = 60_000,
  ) {}

  allow(key: string, now: number = Date.now()): boolean {
    const e = this.hits.get(key);
    if (!e || now >= e.resetAt) {
      if (this.hits.size > 5000) this.prune(now); // bound memory across many IPs
      this.hits.set(key, { count: 1, resetAt: now + this.windowMs });
      return true;
    }
    if (e.count >= this.limit) return false;
    e.count++;
    return true;
  }

  private prune(now: number): void {
    for (const [k, v] of this.hits) if (now >= v.resetAt) this.hits.delete(k);
  }
}

function clientIp(req: IncomingMessage): string {
  const fwd = req.headers["x-forwarded-for"];
  const first = Array.isArray(fwd) ? fwd[0] : fwd?.split(",")[0];
  return (first ?? req.socket?.remoteAddress ?? "unknown").trim();
}

/** Fallback token extraction if the router didn't populate req.params (standalone server). */
function tokenFromPath(url: string | undefined): string | undefined {
  const path = new URL(url ?? "/", "http://localhost").pathname;
  const m = /^\/trust\/([^/]+)\/?$/.exec(path);
  return m ? decodeURIComponent(m[1]) : undefined;
}

function sendHtml(res: ServerResponse, status: number, html: string): void {
  res.statusCode = status;
  res.setHeader("content-type", "text/html; charset=utf-8");
  // A private, per-recipient capability: keep it out of search indexes and shared caches.
  res.setHeader("X-Robots-Tag", "noindex");
  res.setHeader("Cache-Control", "private, no-store");
  res.setHeader("Referrer-Policy", "no-referrer");
  res.end(html);
}

/**
 * The `GET /trust/:token` request handler. Rate-limit → resolve the token to a scoped,
 * audience-safe view → render. Unknown/revoked/missing tokens (and rate-limited requests)
 * never reveal whether a token exists. Exported for tests.
 */
export async function handleTrustRequest(
  getOrch: () => KeptOrchestrator,
  limiter: TrustRateLimiter,
  req: IncomingMessage & { params?: Record<string, string | string[] | undefined> },
  res: ServerResponse,
): Promise<void> {
  if (!limiter.allow(clientIp(req))) {
    res.statusCode = 429;
    res.setHeader("content-type", "text/plain; charset=utf-8");
    res.setHeader("X-Robots-Tag", "noindex");
    res.setHeader("Cache-Control", "private, no-store");
    res.setHeader("Retry-After", "60");
    res.end("Too many requests");
    return;
  }
  const raw = req.params?.token;
  const token = (Array.isArray(raw) ? raw[0] : raw) ?? tokenFromPath(req.url);
  const view = token ? await getOrch().trustPageForToken(token) : null;
  if (!view) {
    sendHtml(res, 404, renderTrustNotFound());
    return;
  }
  sendHtml(res, 200, renderTrustPage(view));
}

/** Build the Bolt customRoute for the trust page (used by keptCustomRoutes). */
export function trustCustomRoute(getOrch: () => KeptOrchestrator, limiter: TrustRateLimiter = new TrustRateLimiter()): CustomRoute {
  return {
    path: "/trust/:token",
    method: "GET",
    handler: (req, res) => {
      handleTrustRequest(getOrch, limiter, req, res).catch((err) => {
        res.statusCode = 500;
        res.end(String(err instanceof Error ? err.message : err));
      });
    },
  };
}
