import type { DraftResult } from '../core/pipeline.js';

/**
 * Canvas export artifact.
 *
 * Produces a Slack Canvas document containing the full questionnaire outcome:
 * - every question
 * - its status (Verified / Grounded / Needs SME)
 * - the drafted / approved answer
 * - evidence permalinks
 * - approval record
 * - invariant statement
 *
 * The returned object can be passed to Slack's canvases.create + canvases.edit
 * APIs, or rendered to Markdown for a file fallback.
 */

const STATE_LABEL: Record<DraftResult['state'], string> = {
  verified: 'Verified',
  grounded: 'Grounded',
  needs_sme: 'Needs SME',
};

export interface CanvasSection {
  type: 'header' | 'paragraph' | 'bullets';
  text?: string;
  items?: string[];
}

export interface CanvasDocument {
  title: string;
  sections: CanvasSection[];
}

export function buildCanvasDocument(
  results: DraftResult[],
  opts: {
    runId: string;
    requesterId: string;
    title?: string;
    generatedAt?: string;
    decisionLog?: boolean;
  },
): CanvasDocument {
  const title = opts.title ?? (opts.decisionLog ? 'Decision Log — Asked & Answered' : 'Questionnaire — Asked & Answered');
  const approved = results.filter((r) => r.state === 'verified' && r.approvedBy);
  const sections: CanvasSection[] = [
    { type: 'header', text: title },
    {
      type: 'paragraph',
      text:
        `Generated by Asked & Answered for <@${opts.requesterId}> ` +
        `at ${opts.generatedAt ?? new Date().toISOString()}. ` +
        `This document is fail-closed: any row without a citation means the agent refused to invent an answer.`,
    },
    {
      type: 'bullets',
      items: [
        `Run ID: \`${opts.runId}\``,
        `Total questions: ${results.length}`,
        `Verified: ${results.filter((r) => r.state === 'verified').length}`,
        `Grounded: ${results.filter((r) => r.state === 'grounded').length}`,
        `Needs SME: ${results.filter((r) => r.state === 'needs_sme').length}`,
      ],
    },
  ];

  if (approved.length > 0) {
    sections.push({ type: 'header', text: 'Decision log — approved answers' });
    sections.push({
      type: 'bullets',
      items: approved.map(
        (r) =>
          `**${r.questionText}** — ${r.answerText ?? ''} ` +
          `(approved by <@${r.approvedBy}> at ${r.approvedAt ?? ''})`,
      ),
    });
  }

  for (const [i, r] of results.entries()) {
    sections.push({ type: 'header', text: `${i + 1}. ${r.questionText}` });
    sections.push({ type: 'paragraph', text: `Status: **${STATE_LABEL[r.state]}**` });

    if (r.state !== 'needs_sme') {
      sections.push({ type: 'paragraph', text: r.answerText ?? '' });
      if ((r.citations ?? []).length > 0) {
        sections.push({
          type: 'bullets',
          items: (r.citations ?? []).map((c) => `Evidence: ${c.permalink}`),
        });
      }
      if (r.approvedBy) {
        sections.push({
          type: 'paragraph',
          text: `Approved by <@${r.approvedBy}> at ${r.approvedAt ?? ''}.`,
        });
      }
    } else {
      sections.push({
        type: 'paragraph',
        text: 'No sufficient workspace evidence was found. This question was routed to a human expert.',
      });
    }
  }

  sections.push({ type: 'header', text: 'Invariant statement' });
  sections.push({
    type: 'paragraph',
    text:
      'Answer text is returned to a requester only if that requester can currently see every citation backing the answer. ' +
      'This invariant is property-tested, live-checked at /invariant, and machine-verified with Z3.',
  });

  return { title, sections };
}

/** Convert a Canvas document to Markdown for file-upload fallback. */
export function canvasToMarkdown(doc: CanvasDocument): string {
  const out: string[] = [`# ${doc.title}`, ''];
  for (const s of doc.sections) {
    switch (s.type) {
      case 'header':
        out.push(`## ${s.text}`, '');
        break;
      case 'paragraph':
        out.push(s.text ?? '', '');
        break;
      case 'bullets':
        for (const item of s.items ?? []) out.push(`- ${item}`);
        out.push('');
        break;
    }
  }
  return out.join('\n');
}

/** Convert a Canvas document to the Slack Canvas API `sections` format. */
export function canvasToApiSections(doc: CanvasDocument): unknown[] {
  return doc.sections.map((s) => {
    switch (s.type) {
      case 'header':
        return { type: 'header', text: { type: 'plain_text', text: s.text ?? '' } };
      case 'paragraph':
        return { type: 'rich_text', elements: [{ type: 'rich_text_section', elements: [{ type: 'text', text: s.text ?? '' }] }] };
      case 'bullets':
        return {
          type: 'rich_text',
          elements: [
            {
              type: 'rich_text_list',
              style: 'bullet',
              elements: (s.items ?? []).map((item) => ({
                type: 'rich_text_section',
                elements: [{ type: 'text', text: item }],
              })),
            },
          ],
        };
      default:
        return { type: 'rich_text', elements: [] };
    }
  });
}
