// Work Post canvas: render (spec §14 template), createOrReplace, appendAgentOutput.
// Fallback chain lives here: canvases.create -> conversations.canvases.create -> Block Kit sentinel.
const store = require('./store');

function name(names, userId) {
  if (!userId) return null;
  return (names && names[userId]) || userId;
}

// meta: { channelId, threadPermalink, createdDate, names: {id: display}, truncated,
//         listPermalink, related: [{permalink, channel, date, note}], evidenceLinks: {ts: url},
//         agentOutput: {title, timestamp, approvedByName, content} | null }
function render(wp, meta) {
  const m = meta;
  const lines = [];
  lines.push(`# 📌 ${wp.title}`, '');
  lines.push(`> ${wp.tldr}`, '');
  const source = m.threadPermalink ? ` · **Source:** [original thread](${m.threadPermalink})` : '';
  const lastActivity = m.lastActivity ? ` · **Last activity:** ${m.lastActivity}` : '';
  lines.push(`**Status:** ${wp.status_guess} · **Created:** ${m.createdDate} via Threadwork${lastActivity}${source}`);
  if (m.truncated) lines.push(`_Structured from the most recent portion of a long thread._`);
  lines.push(`**Participants:** ${wp.participants.map((u) => `@${name(m.names, u)}`).join(', ')}`, '');

  lines.push('---', '');
  lines.push(`## ✅ Decisions`);
  if (wp.decisions.length === 0) lines.push(`_None captured yet._`);
  for (const d of wp.decisions) {
    const by = d.decided_by ? ` — *@${name(m.names, d.decided_by)}*` : '';
    const link = m.evidenceLinks && m.evidenceLinks[d.evidence_ts] ? ` ([context](${m.evidenceLinks[d.evidence_ts]}))` : '';
    lines.push(`- ${d.text}${by}${link}`);
  }
  lines.push('');

  lines.push(`## ❓ Open questions`);
  if (wp.open_questions.length === 0) lines.push(`_None._`);
  for (const q of wp.open_questions) lines.push(`- ${q.text}`);
  lines.push('');

  lines.push(`## 📋 Action items`);
  if (m.listPermalink) {
    lines.push(`Tracked in the [linked Slack List](${m.listPermalink}).`);
  } else {
    for (const t of wp.tasks) {
      const owner = t.suggested_owner ? ` (@${name(m.names, t.suggested_owner)}` + (t.due_hint ? `, due ${t.due_hint})` : ')') : t.due_hint ? ` (due ${t.due_hint})` : '';
      lines.push(`- [ ] ${t.text}${owner}`);
    }
  }
  lines.push('');

  if (m.related && m.related.length > 0) {
    lines.push('---', '');
    lines.push(`## 🔁 Previously discussed`);
    for (const r of m.related) {
      lines.push(`- [#${r.channel} · ${r.date}](${r.permalink})${r.note ? ` — ${r.note}` : ''}`);
    }
    lines.push('');
  }

  lines.push('---', '');
  lines.push(`## 🤖 Agent Output`);
  if (m.agentOutput) {
    lines.push(`### ${m.agentOutput.title} — ${m.agentOutput.timestamp}`);
    lines.push(`*Approved by @${m.agentOutput.approvedByName}*`, '');
    lines.push(m.agentOutput.content);
  } else {
    lines.push(`_(appears after an approved agent run)_`);
  }
  lines.push('', '---', '');
  lines.push(`_Generated by Threadwork${m.threadPermalink ? ` from the [original thread](${m.threadPermalink})` : ''} · conversation in, accountable work out._`);
  return lines.join('\n');
}

let authInfo = null; // cached workspace url + team id
async function permalinkFor(client, canvasId) {
  // ponytail: files.info would need an extra files:read scope; canvas URLs are
  // deterministic (<team_url>docs/<team_id>/<canvas_id>), so construct instead.
  try {
    if (!authInfo) authInfo = await client.auth.test();
    return `${authInfo.url}docs/${authInfo.team_id}/${canvasId}`;
  } catch {
    return null;
  }
}

async function createOrReplace(client, wp, meta, existingCanvasId) {
  const markdown = render(wp, meta);

  if (existingCanvasId) {
    await client.canvases.edit({
      canvas_id: existingCanvasId,
      changes: [{ operation: 'replace', document_content: { type: 'markdown', markdown } }],
    });
    return { canvas_id: existingCanvasId, permalink: await permalinkFor(client, existingCanvasId) };
  }

  // 1. standalone canvas
  try {
    const res = await client.canvases.create({
      title: wp.title,
      document_content: { type: 'markdown', markdown },
    });
    try {
      await client.canvases.access.set({
        canvas_id: res.canvas_id,
        access_level: 'read',
        channel_ids: [meta.channelId],
      });
    } catch (err) {
      console.warn('[canvas] access.set failed (permalink still shared in-thread):', (err.data && err.data.error) || err.message);
    }
    return { canvas_id: res.canvas_id, permalink: await permalinkFor(client, res.canvas_id) };
  } catch (err) {
    console.warn('[canvas] canvases.create failed, trying channel canvas:', (err.data && err.data.error) || err.message);
  }

  // 2. channel canvas
  try {
    const res = await client.conversations.canvases.create({
      channel_id: meta.channelId,
      document_content: { type: 'markdown', markdown },
    });
    return { canvas_id: res.canvas_id, permalink: await permalinkFor(client, res.canvas_id) };
  } catch (err) {
    console.warn('[canvas] channel canvas failed too, Block Kit fallback:', (err.data && err.data.error) || err.message);
  }

  // 3. sentinel: caller posts the work post as a Block Kit message
  return { fallback: 'blocks', markdown };
}

// Re-render the whole document with the agent output section filled (whole-doc replace).
async function appendAgentOutput(client, threadKey, draftMarkdown, approvedByName, timestamp) {
  const record = store.get(threadKey);
  if (!record || !record.canvas_id || !record.workpost_json) {
    throw new Error(`appendAgentOutput: incomplete record for ${threadKey}`);
  }
  const meta = {
    ...record.canvas_meta,
    agentOutput: {
      title: record.workpost_json.proposed_agent_task.action_description,
      timestamp,
      approvedByName,
      content: draftMarkdown,
    },
  };
  await client.canvases.edit({
    canvas_id: record.canvas_id,
    changes: [
      {
        operation: 'replace',
        document_content: { type: 'markdown', markdown: render(record.workpost_json, meta) },
      },
    ],
  });
  return permalinkFor(client, record.canvas_id);
}

// F7: refresh the Canvas "Last activity" line (whole-doc replace, like everything else)
async function touchLastActivity(client, threadKey, dateStr) {
  const record = store.get(threadKey);
  if (!record || !record.canvas_id || !record.workpost_json) return null;
  const meta = { ...record.canvas_meta, lastActivity: dateStr };
  await client.canvases.edit({
    canvas_id: record.canvas_id,
    changes: [
      {
        operation: 'replace',
        document_content: { type: 'markdown', markdown: render(record.workpost_json, meta) },
      },
    ],
  });
  store.save(threadKey, { canvas_meta: meta });
  return permalinkFor(client, record.canvas_id);
}

module.exports = { render, createOrReplace, appendAgentOutput, touchLastActivity, permalinkFor };
